import type { Metadata } from "next";
import localFont from "next/font/local";
import StyledComponentsRegistry from "./_lib/registry";
import "./styles.css";
import Header from "./_components/common/Header";
import { QuestionIcon } from "./_components/common/QuestionIcon";

// 나눔 스퀘어 네오 폰트 설정
const nanumSquareNeo = localFont({
  src: "./fonts/PretendardVariable.woff2",
  variable: "--font-nanum-square-neo",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nanumSquareNeo.className}`}>
        <StyledComponentsRegistry>
          <Header />
          <QuestionIcon />
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
